[package]
name = "bow_proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-buffer = "0.1.6"
i2cdev = "0.6.0"
linux-embedded-hal = "0.4.0"
mpu6050 = "0.1.6"
